### ISSUE TITLE
API Test with Frisby.js

### ISSUE THREAD

**Issue by andreyunugro** [jakartajs/talks#1]
Talk Date: -
Talk Title: API Test with Frisby.js
Length: 30 mins
Twitter-sized Overview: Use frisby.js to test API 
Target audience: BE dev and QA.
Detailed Outlines:
- Intro: What – When – Where – Who – Why
- Frisby.js features: expect, helper, inspector.
- Frisby.js spec and report
- Examples
- Demo
- Closing

**Comment by giosakti** [comment]
Halo bro @andreyunugro jadi mau talk? kita lagi plan event tanggal 24 januari di kantor kudo
