### ISSUE TITLE
Website Performance Over HTTP/2

### ISSUE THREAD

**Issue by tenosiswono** [jakartajs/talks#10]
Talk Date: -
Talk Title: Website Performance Over HTTP/2
Length: 30 mins
Twitter-sized Overview: Understanding benefits in HTTP/2 and how to use it to increase your website performance
Detailed Overview:
- What is HTTP/2?
- Header Field Compression
- Multiplexing Connection
- Server Push
- Push Resources in the Right Order
- Cache digests for HTTP/2 Push
- Conclusion

**Comment by fikriauliya** [comment]
Interesting topic!

**Comment by hengkiardo** [comment]
Thanks bro @tenosiswono

**Comment by fikriauliya** [comment]
Hi @tenosiswono , sorry didn't manage to attend your talk. Is your side available online?

**Comment by fikriauliya** [comment]
Hi @tenosiswono , sorry didn't manage to attend your talk. Is your slide available online?
