### ISSUE TITLE
RapydScript and Rapyd Framework, Python in the Browser and Node

### ISSUE THREAD

**Issue by rafi16jan** [jakartajs/talks#12]
**Full Name**: Farrell Rafi
**Talk Date**: 19 April 2018
**Talk Title**: RapydScript and Rapyd Framework, Python in the Browser and Node
**Length**: 15 Minutes
**Twitter-sized Overview**: I will introduce to you guys a Python to Javascript Transpiler called RapydScript. And my own framework built with it, Rapyd Framework
**Job Title**: IT Head at PT. Tijari Total Solution

**Comment by rozakbuhari** [comment]
+1
