### ISSUE TITLE
Snapshot Test in React Component using Jest and Enzyme

### ISSUE THREAD

**Issue by sujono91** [jakartajs/talks#4]
Date: - 
Title: Snapshot Test in React Component using Jest and Enzyme
Length: 20 - 30 mins
Overview:
How we implement the snapshot test in React component and what about its advantages and disadvantages (case study: Etobee)
Schedule:
Intro about snapshot test
Why and when we use the snapshot test
Demo
Conclusion

**Comment by hengkiardo** [comment]
@sujono91 I'm ok with this topic. Are you good if we make it for September meetup?
Our September meetup should host by Microsoft in their office.

**Comment by sujono91** [comment]
@aredo ok, i'm available on sept meetup
