### ISSUE TITLE
Lightning Talk Proposal for Meetup on August 22 - Creating Custom Libraries for Graphs Based on Javascript - Renaldi Gondosubroto

### ISSUE THREAD

**Issue by renaldig** [jakartajs/talks#5]
Talk Date: 22 August 2017
Talk Title: Creating Custom Libraries for Graphs Based on Javascript
Length: 10 minutes
Twitter-sized Overview (140 characters): Need to create a customized graph? This lightning talk will discuss the Javascript techniques necessary through tools ctx, canvas, and more!
Detailed Overview: Ever wanted to create your own graphs for private or professional reasons but end up using default templates set by other services in the end? It's time for us to get used to customizing our own graphs, especially if we want to use it for corporate means (thus commercializing it)! This lightning talk will show in just 10 minutes how you can get started in creating the said customized graphs using parameters from Javascript such as canvas and ctx and eventually finish up with a graph ready to display data through methods such as jQuery.

**Comment by hengkiardo** [comment]
hi @renaldig, I'm OK with this topic.

Thanks

**Comment by renaldig** [comment]
Sounds good, looking forward to present it at the meeting!

**Comment by hengkiardo** [comment]
bro @renaldig thanks for the lightning talk our last meetup. can you share you source code and slide on our slack group?

**Comment by giosakti** [comment]
disini juga bro @aredo untuk source code & slide, supaya lebih terdokumentasi dengan baik.. kalau di slack suka tenggelam di antara pesan2 baru
