### ISSUE TITLE
Build Your Next Website with React, GatsbyJS and Netlify

### ISSUE THREAD

**Issue by resir014** [jakartajs/talks#6]
**Talk Date:** TBD
**Talk Title:** Build Your Next Website with React, GatsbyJS and Netlify
**Length:** 15min-30min
**Twitter-sized Overview (140 characters):** In this talk we take a dive into GatsbyJS, a new player among static-site generators, which uses React components to create blazing-fast static pages that are easily deployable to services like Netlify.

**Detailed Overview:**

Static sites used to power the internet back in the good old Web 1.0 days, but with the advent of Web 2.0 and dynamic content pages, this practice slowly died out over time, and people moved on to content management systems (CMS) like WordPress. It was only until 2013 that static sites made a comeback, with the arrival of GitHub Pages, which allows building and deploying your websites with Jekyll, a popular static site generator powered by Ruby.

Over time, the number of static site generators have risen, most of them written in a lot of different languages including JavaScript. One of these JavaScript-based static-site generators is GatsbyJS.

GatsbyJS is a blazing-fact static site generator powered by JavaScript and React. It's very extensible and allows you to generate optimised static pages from Markdown files, as well as many other sources. In this talk, we'll go through how you can set up your next website using GatsbyJS, from idea to deployment, as well as the benefits of static sites compared with dynamic-content pages in a traditional CMS.

**Brief Outline:**

* A brief history of static site generators
* Why static websites? (performance, JAMstack, etc)
* Introduction to GatsbyJS
* The GatsbyJS workflow (initialising, building, deploying via Netlify, plugins, demos?)
* Conclusion

**Comment by giosakti** [comment]
Halo bro @resir014 jadi mau talk? kita lagi plan event tanggal 24 januari di kantor kudo

**Comment by resir014** [comment]
Bisa mas @giosakti, ditunggu untuk schedule-nya.

**Comment by giosakti** [comment]
oke udah di publish ya, bisa dicek di meetup.com/jakartajs
