### ISSUE TITLE
Leverage your React Native App

### ISSUE THREAD

**Issue by arufian** [jakartajs/talks#7]
**Talk Date**: January
**Talk Title**: Leverage your React Native App
**Length**: 20-30
**Twitter-sized Overview (140 characters)**: Many people saying that React Native app is slower than Native App. That's not true, we can make it faster than any other native app. Here are the tricks.
**Detailed Overview**:
- Intro to React Native rendering
- PureComponent and shouldcomponentUpdate for the win
- Don't forget to assign key on every list
- Rendering Blocking
- How to prevent rendering Blocking
- FlatList vs ListView, SectionList vs ScrollView
- Advance Optimization Rendering:
    - Utilize RequestAnimationFrame
    - next-frame
    - whyDidYouUpdate and use Perf monitor to watch FPS

**Comment by giosakti** [comment]
Halo bro @arufian jadi mau talk? kita lagi plan event tanggal 24 januari di kantor kudo

**Comment by arufian** [comment]
siap mas @giosakti , tolong di schedule 🙏

**Comment by giosakti** [comment]
oke @arufian  udah di publish ya, bisa dicek di meetup.com/jakartajs
